In [1]:
import pandas as pd
data = pd.read_csv("bank_reviews3.csv")
data.head()

,author,date,address,bank,rating,review_title_by_user,review,bank_image,rating_title_by_user,useful_count
0,AMRENDRA T,"Mar 21, 2020",New delhi,SBI,4.0,"""Best saving""",State Bank Of India is located nearby in our a...,https://static.bankbazaar.com/images/common/ba...,Great!,133
1,BISHWA,"Mar 20, 2020",Kolkata,SBI,5.0,"""Good service""","I have my salary account in SBI, when I applie...",https://static.bankbazaar.com/images/common/ba...,Blown Away!,89
2,SANTOSH,"Mar 20, 2020",Hooghly,Axis Bank,5.0,"""Excellent Service""",I am using Axis bank saving account for the p...,https://static.bankbazaar.com/images/common/ba...,Blown Away!,48
3,MAHADEV,"Mar 20, 2020",Pune,HDFC Bank,5.0,"""Excellent service""",I have my salary bank account in HDFC bank for...,https://static.bankbazaar.com/images/common/ba...,Blown Away!,52
4,R,"Mar 20, 2020",Bangalore,review,5.0,"""Good account""","Close to around 10 years, I am holding this Co...",https://static.bankbazaar.com/images/common/ba...,Blown Away!,22

In [2]:
train = data[["bank","review", "rating"]]
train.head()

        bank                                             review  rating
0        SBI  State Bank Of India is located nearby in our a...     4.0
1        SBI  I have my salary account in SBI, when I applie...     5.0
2  Axis Bank  I am using Axis bank saving account for the  p...     5.0
3  HDFC Bank  I have my salary bank account in HDFC bank for...     5.0
4     review  Close to around 10 years, I am holding this Co...     5.0

In [3]:
test2 = train[0:500]
test2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   bank    500 non-null    object
 1   review  500 non-null    object
 2   rating  500 non-null    float64
dtypes: float64(1), object(2)
memory usage: 11.8+ KB

In [ ]:
test.to_csv("test_sample_